options:
  max-warnings: 50
files:
  include: 'src/**/*.s+(a|c)ss'
  ignore:
    - 'node_modules/**/*.*'
rules:
  no-vendor-prefixes: 1
  no-ids: 0
  property-sort-order: 0
  empty-line-between-blocks: 1
  class-name-format: 0
  leading-zero: 0
  nesting-depth:
    - 1
    -
      max-depth: 4
  quotes:
    - 1
    -
      style: double
  no-duplicate-properties: 1
  no-important: 0
  mixins-before-declarations: 0
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  no-misspelled-properties: 1
  no-mergeable-selectors: 0
pseudo-element: 0
